// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTOSHNNwFbjWOTyI0YwcnFZjCPqM_whxo',
    appId: '1:670008296881:web:0c95accd22dd696e962990',
    messagingSenderId: '670008296881',
    projectId: 'fir-flutter-projet2',
    authDomain: 'fir-flutter-projet2.firebaseapp.com',
    storageBucket: 'fir-flutter-projet2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnC8k2cKF2fYQsQukUXRke0I3VIyzvcvY',
    appId: '1:670008296881:android:750608d37b9a122b962990',
    messagingSenderId: '670008296881',
    projectId: 'fir-flutter-projet2',
    storageBucket: 'fir-flutter-projet2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfq7isp_IKZ6b4aCRWBbAlAvpxNjbVDGc',
    appId: '1:670008296881:ios:75fc3d023f7cebd3962990',
    messagingSenderId: '670008296881',
    projectId: 'fir-flutter-projet2',
    storageBucket: 'fir-flutter-projet2.appspot.com',
    iosClientId: '670008296881-r9mis32a5hd8cj0um072ap50o2v8alir.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjet2',
  );
}
